--- #YAML:1.0
name:                Regexp-HTMLify
version:             0.001
abstract:            Highlight regular expression capture buffers and matches using HTML and CSS
license:             ~
author:              
    - Niels van Dijke <CpanDotOrgAtPerlboyDotNet>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    CGI:                           0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
