--- #YAML:1.0
name:               Regexp-HTMLify
version:            0.002
abstract:           Highlight regular expression capture buffers and matches using HTML and CSS
author:
    - Niels van Dijke <CpanDotOrgAtPerlboyDotNet>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    CGI:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
